version: '3'

tasks:
  default:
    cmds:
      - task: prepare
      - task: test

  test:
    desc: Test and lint.
    cmds:
      - go mod verify
      - go test -shuffle on ./...
      - govulncheck ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:latest golangci-lint run --enable gosec --exclude "G404" --timeout 3m0s ./...
    sources:
      - ./go.mod
      - '**/*.go'

  prepare:
      - go mod tidy -v -go=1.21

  clean:
    desc: Initialize module and build cache, and remake go.sum file.
    cmds:
      - rm -f ./go.sum
      - go clean -cache
      - go clean -modcache
